ALTER TABLE teams DISABLE ROW LEVEL SECURITY;
ALTER TABLE team_pokemon DISABLE ROW LEVEL SECURITY;

GRANT ALL ON teams TO anon;
GRANT ALL ON team_pokemon TO anon;
GRANT USAGE ON SCHEMA public TO anon;
